### ISSUE TITLE
Sign into a Sandbox?

### ISSUE THREAD

**Issue by rpbeam** [kylpo/salesforce1-simulator#1]
Will the simulator connect to a sandbox?

Thanks
Rodney

**Comment by kylpo** [comment]
Sure can! Please see the "How do I connect this to a Sandbox org?" section of this FAQ: https://docs.google.com/document/d/1EdAE30b9K-Npqc0Z8QFXPzjwgvkErk__L8yHNDhMv8s/edit?usp=sharing
